services:
  - type: web
    name: task-management-backend
    env: go
    buildCommand: go build -o main .
    startCommand: ./main
    plan: free
    envVars:
      - key: PORT
        value: 8080
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
